In [10]:
import numpy as np

## ahora veremos como mostrar la forma de los arrays creados con numpy

# creando un array 3D
arr_3d = np.zeros((3,3,3))

# y lo imprimimos
print(arr_3d)

# vemos su forma
print("la forma es: {}".format(arr_3d.shape))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
la forma es: (3, 3, 3)


In [12]:
# ahora veremos como convertir una lista de python a un array en numpy

# primero creamos una lista 
lista = [1,2,3,45,5,6,7,8,8]
lista_array = np.array(lista)

print(lista_array)
print(lista_array.shape)

[ 1  2  3 45  5  6  7  8  8]
(9,)


In [28]:
# crear un array de inicializando con ceros
array_ceros = np.zeros(10)
print(array_ceros)
array_ceros_dimensiones = np.zeros((5,2,3))
print(array_ceros_dimensiones)

print("y la forma es: {}".format(array_ceros_dimensiones.shape))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
y la forma es: (5, 2, 3)


In [ ]:
# crear un array dando un rango
# para dar el rango hay opciones como en una lista normal
# si dejas un numero solo -> (numero) : ira desde el cero hasta en (numero - 1)
# si pones dos numeros  -> (numero_inicial, numero_final) : desde el inicial hasta el (final - 1)
# si pones tres numeros -> (numero_inicial, numero_final, intervalo): va como el anterior pero el tercer valor en la razon a la que va a aumentar
# ahora veremos los ejemplos
array_rango_1 = np.arange(100)
array_rango_2 = np.arange(0,100)
array_rango_3 = np.arange(0,100,2)
print(array_rango_1)
print(array_rango_2)
print(array_rango_3)

In [ ]:
# si quieres hallar los espacios entre dos numeros, usaremos linspace
# .linspace(inicio, fin, numero_de_espacios)
array_espacios = np.linspace(0,10,100)
print(array_espacios)

In [40]:
# ahora veremos la diferencia entre un array normal y otro convertido a un entero
cube_normal = np.zeros((3,3,3)) + 1
cube_integer = np.zeros((3,3,3)).astype(int) + 1
cube_float = np.ones((3, 3, 3)).astype(np.float16)

# podran notar el punto decimal que se aplica por defecto
print("Cubo normal creado: \n{}".format(cube_normal))
print("Cubo de integers creado: \n{}".format(cube_integer))
print("Cubo de flotantes creado: \n{}".format(cube_float))

Cubo normal creado: 
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
Cubo de integers creado: 
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
Cubo de flotantes creado: 
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [46]:
# tambien podemos usar tipos de datos desde numpy
array_entero = np.zeros(3, dtype=int)
print("el array de enteros con tipo de datos de python: \n{}".format(array_entero))

array_flotante = np.zeros(3, dtype=np.float32)
print("el array de enteros con tipo de datos de numpy: \n{}".format(array_flotante))
# y porque usamos np.float32? porque en python no existe nativamente exactamente float32

el array de enteros con tipo de datos de python: 
[0 0 0]
el array de enteros con tipo de datos de numpy: 
[0. 0. 0.]


In [49]:
# ahora veremos algo interesante

# creamos un array de 1000 elementos 
arr_1d = np.arange(1000)
print(arr_1d)

# y los podemos reformar a una matriz 3d y numpy se encarga de manera automatica de esto
arr_3d_1 = arr_1d.reshape((10,10,10))
print(arr_3d_1)

# y tambien puede ser cambiado de esta forma
arr_3d_2 = np.reshape(arr1s, (10, 10, 10))
print(arr_3d_2)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

NameError: name 'arr1s' is not defined

In [55]:
arr4d = np.zeros((10, 10, 10, 10))
print(arr4d)

arr1d = arr4d.ravel()
print(arr1d)
print("la forma es: {}".format(arr1d.shape))

[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  ...

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 

In [59]:
recarr = np.zeros((2,), dtype=('i4,f4,a10'))
toadd = [(1,2.,'Hello'),(2,3.,"World")]
recarr[:] = toadd
print(recarr)
recarr = np.zeros((2,), dtype=('i4,f4,a10'))
print(recarr)

col1 = np.arange(2) + 1
col2 = np.arange(2, dtype=np.float32)
col3 = ['Hello', 'World']

print(col1)
print(col2)
print(col3)

[(1, 2., b'Hello') (2, 3., b'World')]
[(0, 0., b'') (0, 0., b'')]
[1 2]
[0. 1.]
['Hello', 'World']
